### ISSUE TITLE
Build plugin

### ISSUE THREAD

**Issue by kneal** [go-vela/vela-kubernetes#1]
## Description

_What is your idea?_

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

## Definition of Done

_What is the end goal of this story?_

## Effort  (Optional)

_Estimated effort to complete this story? (Best Guess e.g. 1-2 days)_

## Impacted Personas (Optional)

_Which personas will benefit from completing this story? (Users, Administrators, etc)_

**Comment by jbrockopp** [comment]
Initial commit published:

https://github.com/go-vela/vela-kubernetes/commit/9a7044bce2031a117e3f771f82989a9db794fafa

**Comment by jbrockopp** [comment]
Add go module support:

https://github.com/go-vela/vela-kubernetes/pull/2

**Comment by jbrockopp** [comment]
Created Docker repo:

https://hub.docker.com/r/target/vela-kubernetes

**Comment by jbrockopp** [comment]
Add Actions pipeline:

https://github.com/go-vela/vela-kubernetes/pull/3

**Comment by jbrockopp** [comment]
Add CI configuration files:

https://github.com/go-vela/vela-kubernetes/pull/4

**Comment by jbrockopp** [comment]
Add plugin shell logic:

https://github.com/go-vela/vela-kubernetes/pull/5

**Comment by jbrockopp** [comment]
Add cmds for `kubectl`:

https://github.com/go-vela/vela-kubernetes/pull/6

**Comment by jbrockopp** [comment]
Add validate logic:

https://github.com/go-vela/vela-kubernetes/pull/7

**Comment by jbrockopp** [comment]
Write Kubernetes config:

https://github.com/go-vela/vela-kubernetes/pull/8

**Comment by jbrockopp** [comment]
Add `Status` to plugin:

https://github.com/go-vela/vela-kubernetes/pull/9

**Comment by jbrockopp** [comment]
Add `Patch` to plugin:

https://github.com/go-vela/vela-kubernetes/pull/10

**Comment by jbrockopp** [comment]
Add `Apply` to plugin:

https://github.com/go-vela/vela-kubernetes/pull/11

**Comment by jbrockopp** [comment]
Refactor `Config` for plugin:

https://github.com/go-vela/vela-kubernetes/pull/12

**Comment by jbrockopp** [comment]
Add `Command()` methods for plugin:

https://github.com/go-vela/vela-kubernetes/pull/13

**Comment by jbrockopp** [comment]
Remove dead cmd code:

https://github.com/go-vela/vela-kubernetes/pull/14

**Comment by jbrockopp** [comment]
Add `Exec()` methods for plugin:

https://github.com/go-vela/vela-kubernetes/pull/15

**Comment by jbrockopp** [comment]
Refactor `Patch` for plugin:

https://github.com/go-vela/vela-kubernetes/pull/16

**Comment by jbrockopp** [comment]
Add ability to provide output to plugin:

https://github.com/go-vela/vela-kubernetes/pull/17

**Comment by jbrockopp** [comment]
Enable watching status of resources:

https://github.com/go-vela/vela-kubernetes/pull/18

**Comment by jbrockopp** [comment]
Refactor `Container` for plugin:

https://github.com/go-vela/vela-kubernetes/pull/19

**Comment by jbrockopp** [comment]
Enable setting `kubectl` cluster:

https://github.com/go-vela/vela-kubernetes/pull/20

**Comment by jbrockopp** [comment]
Add method for executing plugin:

https://github.com/go-vela/vela-kubernetes/pull/21

**Comment by jbrockopp** [comment]
Add plugin template:

https://github.com/go-vela/vela-kubernetes/pull/22

**Comment by jbrockopp** [comment]
Improve `Makefile`:

https://github.com/go-vela/vela-kubernetes/pull/23

**Comment by jbrockopp** [comment]
Add pattern for patching containers:

https://github.com/go-vela/vela-kubernetes/pull/25

**Comment by jbrockopp** [comment]
Allow passing files for patching containers:

https://github.com/go-vela/vela-kubernetes/pull/26

**Comment by jbrockopp** [comment]
Only require kube config file:

https://github.com/go-vela/vela-kubernetes/pull/27

**Comment by jbrockopp** [comment]
Add action for plugin:

https://github.com/go-vela/vela-kubernetes/pull/28

**Comment by jbrockopp** [comment]
Use single `Patch` pattern:

https://github.com/go-vela/vela-kubernetes/pull/29

**Comment by jbrockopp** [comment]
Write path to directory before writing file:

https://github.com/go-vela/vela-kubernetes/pull/30

**Comment by jbrockopp** [comment]
Output version with `Config`:

https://github.com/go-vela/vela-kubernetes/pull/31

**Comment by jbrockopp** [comment]
Add plugin usage docs:

https://github.com/go-vela/vela-kubernetes/pull/32

**Comment by jbrockopp** [comment]
Allow setting path to kubeconfig:

https://github.com/go-vela/vela-kubernetes/pull/33

**Comment by jbrockopp** [comment]
Switch patch pattern from YAML to JSON:

https://github.com/go-vela/vela-kubernetes/pull/36

**Comment by jbrockopp** [comment]
Do not set output by default:

https://github.com/go-vela/vela-kubernetes/pull/37

**Comment by jbrockopp** [comment]
Add plugin content to documentation site:

https://github.com/go-vela/docs/pull/111

**Comment by jbrockopp** [comment]
Plugin released:

https://github.com/go-vela/vela-kubernetes/releases/tag/v0.1.0
